[package]
name = "yoga"
description = "Rust bindings for Facebook's Yoga, a Flexbox layout engine"
license = "MIT"
repository = "https://github.com/bschwind/yoga-rs"
version = "0.2.0"
authors = ["Brian Schwind <brianmschwind@gmail.com>"]
build = "build.rs"

[features]
default = []
serde_support = ["serde", "serde_derive", "ordered-float/serde"]

[build-dependencies]
bindgen = "0.23.0"
gcc = "0.3.54"

[dependencies]
self-tokenize-macro = { git = "https://github.com/victorporof/rust-self-tokenize.git" }
self-tokenize-trait = { git = "https://github.com/victorporof/rust-self-tokenize.git" }
ordered-float = "0.5.0"
serde = { version = "1.0.27", optional = true }
serde_derive = { version = "1.0.27", optional = true }
